import { describe, expect, it } from 'vitest'
import { mkdtempSync, rmSync, writeFileSync, readFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { forgeLlmsTxt, firstParagraph } from '../src/forge.js'

function makeProject(files: Record<string, string>): string {
  const dir = mkdtempSync(path.join(tmpdir(), 'dsh-llms-forge-'))
  for (const [rel, content] of Object.entries(files)) {
    const target = path.join(dir, rel)
    writeFileSync(target, content, 'utf8')
  }
  return dir
}

describe('firstParagraph', () => {
  it('skips headings and code fences', () => {
    const readme = ['# Title', '', '```', 'code', '```', '', 'The real intro line here.'].join('\n')
    expect(firstParagraph(readme)).toBe('The real intro line here.')
  })
  it('returns null for empty readme', () => {
    expect(firstParagraph('# Only heading')).toBeNull()
  })
})

describe('forgeLlmsTxt', () => {
  it('builds content from package.json + README without writing', async () => {
    const dir = makeProject({
      'package.json': JSON.stringify({ name: 'dsh-demo', version: '0.1.0', description: 'A demo plugin.', license: 'MIT', keywords: ['dsh', 'demo'] }),
      'README.md': '# dsh-demo\n\nLonger readme body here.',
    })
    try {
      const result = await forgeLlmsTxt(dir)
      expect(result.schema).toBe('dsh-llms-forge/v1')
      expect(result.ok).toBe(true)
      expect(result.written).toBe(false)
      expect(result.content).toContain('# dsh-demo')
      expect(result.content).toContain('A demo plugin.')
      expect(result.content).toContain('License: MIT')
      expect(result.content).toContain('Keywords: dsh, demo')
      expect(result.content).toContain('Install: dsh plugin add dsh-demo')
      expect(result.content).toContain('Generated by dsh-llms-forge')
      expect(() => readFileSync(path.join(dir, 'llms.txt'))).toThrow()
    } finally {
      rmSync(dir, { recursive: true, force: true })
    }
  })

  it('falls back to README paragraph when description is missing', async () => {
    const dir = makeProject({
      'package.json': JSON.stringify({ name: 'dsh-demo', version: '0.1.0' }),
      'README.md': '# dsh-demo\n\nThe fallback sentence from README.',
    })
    try {
      const result = await forgeLlmsTxt(dir)
      expect(result.ok).toBe(false)
      expect(result.warnings.some((w) => w.includes('no description'))).toBe(true)
      expect(result.content).toContain('The fallback sentence from README.')
    } finally {
      rmSync(dir, { recursive: true, force: true })
    }
  })

  it('warns when README is missing', async () => {
    const dir = makeProject({
      'package.json': JSON.stringify({ name: 'dsh-demo', version: '0.1.0', description: 'Only desc.' }),
    })
    try {
      const result = await forgeLlmsTxt(dir)
      expect(result.warnings.some((w) => w.includes('README.md is missing'))).toBe(true)
    } finally {
      rmSync(dir, { recursive: true, force: true })
    }
  })

  it('fails cleanly when package.json is missing', async () => {
    const dir = makeProject({})
    try {
      const result = await forgeLlmsTxt(dir)
      expect(result.ok).toBe(false)
      expect(result.content).toBe('')
      expect(result.warnings[0]).toContain('package.json is missing')
    } finally {
      rmSync(dir, { recursive: true, force: true })
    }
  })

  it('refuses to overwrite without overwrite=true', async () => {
    const dir = makeProject({
      'package.json': JSON.stringify({ name: 'dsh-demo', version: '0.1.0', description: 'Desc.' }),
      'llms.txt': '# old',
    })
    try {
      const result = await forgeLlmsTxt(dir, { write: true })
      expect(result.written).toBe(false)
      expect(result.warnings.some((w) => w.includes('already exists'))).toBe(true)
      expect(readFileSync(path.join(dir, 'llms.txt'), 'utf8')).toBe('# old')
    } finally {
      rmSync(dir, { recursive: true, force: true })
    }
  })

  it('writes when write=true and replaces with overwrite=true', async () => {
    const dir = makeProject({
      'package.json': JSON.stringify({ name: 'dsh-demo', version: '0.1.0', description: 'Desc.' }),
      'llms.txt': '# old',
    })
    try {
      const result = await forgeLlmsTxt(dir, { write: true, overwrite: true })
      expect(result.written).toBe(true)
      expect(readFileSync(path.join(dir, 'llms.txt'), 'utf8')).toContain('# dsh-demo')
    } finally {
      rmSync(dir, { recursive: true, force: true })
    }
  })
})