/**
 * llms.txt generation for dsh plugin repositories.
 *
 * Reads package.json + README and produces a deterministic, AI-readable
 * llms.txt (the file AI agents are told to look for first). Zero runtime
 * dependencies; writing is opt-in via `write` so the tool is read-only by
 * default.
 * @module dsh-llms-forge/forge
 */

import { readFile, writeFile, access } from 'node:fs/promises'
import path from 'node:path'

export interface ForgeOptions {
  /** Write the file to disk (read-only by default). */
  write?: boolean
  /** Replace an existing llms.txt (refused without this). */
  overwrite?: boolean
}

export interface ForgeResult {
  schema: 'dsh-llms-forge/v1'
  target: string
  ok: boolean
  path: string
  written: boolean
  warnings: string[]
  content: string
}

interface Manifest {
  name?: unknown
  version?: unknown
  description?: unknown
  license?: unknown
  homepage?: unknown
  keywords?: unknown
  main?: unknown
  bin?: unknown
  [key: string]: unknown
}

async function readText(file: string): Promise<string | null> {
  try {
    return await readFile(file, 'utf8')
  } catch {
    return null
  }
}

async function exists(file: string): Promise<boolean> {
  try {
    await access(file)
    return true
  } catch {
    return false
  }
}

/** First non-empty, non-heading, non-code paragraph of a README. */
export function firstParagraph(readme: string): string | null {
  let inFence = false
  for (const rawLine of readme.split(/\r?\n/)) {
    const line = rawLine.trim()
    if (line.startsWith('```')) {
      inFence = !inFence
      continue
    }
    if (inFence) continue
    if (line === '' || line.startsWith('#')) continue
    return line.length > 280 ? `${line.slice(0, 277)}...` : line
  }
  return null
}

/** The repo name to use as the document title. */
export function repoTitle(name: unknown, dir: string): string {
  if (typeof name === 'string' && name.trim() !== '') return name.trim()
  return path.basename(path.resolve(dir))
}

/** Build the llms.txt content deterministically. */
export function buildContent(
  title: string,
  description: string,
  facts: string[],
): string {
  const lines: string[] = []
  lines.push(`# ${title}`)
  lines.push('')
  lines.push(description)
  if (facts.length > 0) {
    lines.push('')
    lines.push('## Key facts')
    lines.push('')
    for (const fact of facts) lines.push(`- ${fact}`)
  }
  lines.push('')
  lines.push('> Generated by dsh-llms-forge. Keep this file in sync with README.md and package.json.')
  return lines.join('\n') + '\n'
}

/**
 * Forge (and optionally write) llms.txt for the directory `dir`.
 */
export async function forgeLlmsTxt(dir: string, options: ForgeOptions = {}): Promise<ForgeResult> {
  const target = path.resolve(dir)
  const warnings: string[] = []
  const outPath = path.join(target, 'llms.txt')

  const manifestRaw = await readText(path.join(target, 'package.json'))
  if (manifestRaw === null) {
    return {
      schema: 'dsh-llms-forge/v1',
      target,
      ok: false,
      path: outPath,
      written: false,
      warnings: ['package.json is missing — nothing to forge'],
      content: '',
    }
  }

  let manifest: Manifest
  try {
    manifest = JSON.parse(manifestRaw) as Manifest
  } catch {
    return {
      schema: 'dsh-llms-forge/v1',
      target,
      ok: false,
      path: outPath,
      written: false,
      warnings: ['package.json is not valid JSON'],
      content: '',
    }
  }

  const readme = await readText(path.join(target, 'README.md'))
  let description: string
  if (typeof manifest.description === 'string' && manifest.description.trim() !== '') {
    description = manifest.description.trim()
  } else {
    const paragraph = readme === null ? null : firstParagraph(readme)
    if (paragraph === null) {
      warnings.push('No description in package.json and no README.md paragraph found')
      description = 'No description available.'
    } else {
      warnings.push('package.json has no description; using the first README paragraph')
      description = paragraph
    }
  }
  if (readme === null) warnings.push('README.md is missing; add one for a useful llms.txt')

  const facts: string[] = []
  if (typeof manifest.name === 'string' && manifest.name.trim() !== '') {
    facts.push(`Install: dsh plugin add ${manifest.name.trim()}`)
  }
  if (typeof manifest.license === 'string' && manifest.license !== '') {
    facts.push(`License: ${manifest.license}`)
  }
  if (typeof manifest.homepage === 'string' && manifest.homepage !== '') {
    facts.push(`Homepage: ${manifest.homepage}`)
  }
  if (Array.isArray(manifest.keywords) && manifest.keywords.length > 0) {
    facts.push(`Keywords: ${manifest.keywords.slice(0, 12).join(', ')}`)
  }
  if (typeof manifest.main === 'string' && manifest.main !== '') {
    facts.push(`Entry: ${manifest.main}`)
  }
  if (typeof manifest.bin === 'object' && manifest.bin !== null) {
    const bins = Object.keys(manifest.bin as Record<string, unknown>)
    if (bins.length > 0) facts.push(`CLI: ${bins.join(', ')}`)
  }
  if (typeof manifest.version === 'string' && manifest.version !== '') {
    facts.push(`Version: ${manifest.version}`)
  }

  const content = buildContent(repoTitle(manifest.name, target), description, facts)

  const outExists = await exists(outPath)
  let written = false
  if (options.write === true) {
    if (outExists && options.overwrite !== true) {
      warnings.push('llms.txt already exists; pass overwrite=true to replace it')
    } else {
      await writeFile(outPath, content, 'utf8')
      written = true
    }
  }

  return {
    schema: 'dsh-llms-forge/v1',
    target,
    ok: warnings.length === 0,
    path: outPath,
    written,
    warnings,
    content,
  }
}